name: Emergency review bypass

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write

jobs:
  approve:
    name: Approve
    if: github.event.label.name == 'emergency'
    steps:
      - name: Approve
        uses: ./.github/workflows/actions/emergency-action