name: Emergency review bypass
on:
  pull_request:
    types:
      - labeled
permissions:
  pull-requests: write
jobs:
  approve:
    name: Approve
    if: github.event.label.name == 'emergency'
    uses: ./.github/actions/emergency-action.yaml
    secrets: inherit
